config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'inicio#index'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }
    resources :emails
    mount Ckeditor::Engine => '/ckeditor'
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :pages, only: [:show]
    resources :searches
    resources :contacts, only: [:create]
    get "aica", to: "aica#index"
    get 'i+d', to: "investigacion#index", as: :investigacion
    get "productos", to: "products#index"
    get "noticias", to: "posts#index"
    get 'noticias/:id', to: 'posts#show', as: :post
    get 'productos/:id', to: 'products#show', as: :product
    get "productos_lista", to: "productos#index"
    get :search, controller: :main
    get '*path' => redirect('/')
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
  	can :read, :all  
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
	if user.superadmin_role?
	      can :dashboard, :all
	      can :access, :rails_admin
	      can :manage, :all
	end
	if user.supervisor_role?
		  can :dashboard, :all
	      can :access, :rails_admin
	      can :manage, [User, Post]
	end
    
  end
end

app/models/category.rb
class Category < ApplicationRecord

	has_and_belongs_to_many :posts		

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject,   :validate => true
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => %("#{subject}"),
      :to => "damiansarracent89@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end	

app/models/email.rb
class Email < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :asset,
    :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }
    validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
    validates :asset, attachment_presence: true
    validates_with AttachmentPresenceValidator, attributes: :asset
end

app/models/page.rb
class Page < ApplicationRecord
	translates :body
end

app/models/post.rb
class Post < ApplicationRecord

  translates :title, :description, :body

  extend FriendlyId
  friendly_id :title, :use => :slugged

  

  has_and_belongs_to_many :categories

  has_attached_file :asset, styles: { large: "771x365>" , medium: "560x271>", thumb: "571x181#"}
  validates_attachment_content_type :asset, content_type: /\Aimage\/.*\z/
  validates :asset, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :asset
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :pharmaceuticalform, :inverse_of => :products

  belongs_to :pharmaceuticalgroup, :inverse_of => :products

  extend FriendlyId
    friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end

	has_attached_file :asset, styles: { medium: "270x309>"}
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  validates :asset, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :asset

  has_attached_file :document
  validates_attachment :document, content_type: { content_type: "application/pdf" }
  /validates :document, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :document/

  scope :order_name, ->{ order('name') }
  scope :most_recent, ->{ order(id: :desc) }
  scope :order_name_a, ->{ where("name LIKE ?", "a%").order('name') }
  scope :order_name_b, ->{ where("name LIKE ?", "b%").order('name') }
  scope :order_name_c, ->{ where("name LIKE ?", "c%").order('name') }
  scope :order_name_d, ->{ where("name LIKE ?", "d%").order('name') }
  scope :order_name_e, ->{ where("name LIKE ?", "e%").order('name') }
  scope :order_name_f, ->{ where("name LIKE ?", "f%").order('name') }
  scope :order_name_g, ->{ where("name LIKE ?", "g%").order('name') }
  scope :order_name_h, ->{ where("name LIKE ?", "h%").order('name') }
  scope :order_name_i, ->{ where("name LIKE ?", "i%").order('name') }
  scope :order_name_j, ->{ where("name LIKE ?", "j%").order('name') }
  scope :order_name_k, ->{ where("name LIKE ?", "k%").order('name') }
  scope :order_name_l, ->{ where("name LIKE ?", "l%").order('name') }
  scope :order_name_m, ->{ where("name LIKE ?", "m%").order('name') }
  scope :order_name_n, ->{ where("name LIKE ?", "n%").order('name') }
  scope :order_name_o, ->{ where("name LIKE ?", "o%").order('name') }
  scope :order_name_p, ->{ where("name LIKE ?", "p%").order('name') }
  scope :order_name_q, ->{ where("name LIKE ?", "q%").order('name') }
  scope :order_name_r, ->{ where("name LIKE ?", "r%").order('name') }
  scope :order_name_s, ->{ where("name LIKE ?", "s%").order('name') }
  scope :order_name_t, ->{ where("name LIKE ?", "t%").order('name') }
  scope :order_name_u, ->{ where("name LIKE ?", "u%").order('name') }
  scope :order_name_v, ->{ where("name LIKE ?", "v%").order('name') }
  scope :order_name_w, ->{ where("name LIKE ?", "w%").order('name') }
  scope :order_name_x, ->{ where("name LIKE ?", "x%").order('name') }
  scope :order_name_y, ->{ where("name LIKE ?", "y%").order('name') }
  scope :order_name_z, ->{ where("name LIKE ?", "z%").order('name') }
end

app/models/search.rb
class Search < ApplicationRecord
  def products
    @products = find_products
  end
  
  private

  def find_products
    products = Product.order(:name)
    products = products.where(pharmaceuticalform_id: pharmaceuticalform_id) if pharmaceuticalform_id.present?
    products = products.where(pharmaceuticalgroup_id: pharmaceuticalgroup_id) if pharmaceuticalgroup_id.present?
    products
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def create
    @search = Search.create!(allowed_params)
    redirect_to @search
  end

  def update
    @search = Search.create!(allowed_params)
    redirect_to @search
  end
  
  def show
    @search = Search.new
    @search = Search.find(params[:id])
  end
  
  private
  
  def allowed_params
    params.require(:search).permit!
  end
end

app/helpers/aica_helper.rb
module AicaHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sends_helper.rb
module SendsHelper
end

app/views/searches/_portafolio.html.erb
<blockquote class="blockquote block-quote-aica">
    <p class="dinpro-regular title-aica mb-0"><%= t :product_portfolio %></p> 
  </blockquote>
  <%= form_for @search do |f| %>
  <div class="row">
     <div class="col-md-2">
       <ul class="list-inline">
          <li class="list-inline-item">
            <%= link_to t('all_button'), productos_path, class:"list-inline-item inline-item dinpro-light p-color-gray btn-all" %>
          </li>
          <li class="list-inline-item inline-item dinpro-light p-color-gray">
            /
          </li>
          <li class="list-inline-item inline-item dinpro-light p-color-gray">
            <%= f.submit t('filter_button'), class:"btn-filter" %>
          </li>
        </ul>
     </div>
   <div class="col-md-7">
      <ul class="list-inline">
        <li class="list-inline-item">        
          <div class="combo-box calibril">
            <%= f.collection_select :pharmaceuticalform_id, Pharmaceuticalform.order(:name), :id, :name, include_blank: true, class: "mdb-select" %>
          </div>
        </li>
        <li class="list-inline-item">
          <div class="combo-box calibril">
            <%= f.collection_select :pharmaceuticalgroup_id, Pharmaceuticalgroup.order(:name), :id, :name, include_blank: true, class: "mdb-select" %>
          </div>
        </li>
      </ul>
   </div>
   <div class="col-md-3">
      <ul class="list-inline pull-right">
        <li class="list-inline-item inline-item-views">
          <%= link_to "", productos_lista_path, class:"dinpro-regular icon-lista" %>
        </li>
        <li class="list-inline-item inline-item">
          <%= link_to "", productos_path, class:"dinpro-regular icon-miniaturas-on" %>
        </li>
      </ul>
   </div>
  </div>
   <% end %>

app/views/searches/show.html.erb
<% provide(:page_title, t('products_title') )%>
<% provide(:product_active, 'active')%>
<section class="products">
  <%= render "portafolio" %>
  <hr class="hr-margins-products">
  <% if @search.products.empty? %>
    <div class="wrapper-search">
  		<h1 class="dinpro-regular emp-lab-aica color-title-aica text-uppercase">No hay resultados para su búsqueda.
</h1>
  	</div>
  <% else %>
  <div class="row">
    <%= render @search.products %>
  </div>
  <% end %>
  <hr class="hr-margins-paginate">
</section>